version: '3.8'

services:
  smash-karts-bot:
    build: .
    container_name: smash-karts-bot
    ports:
      - "5000:5000"   # Flask web interface
      - "6080:6080"   # noVNC
    volumes:
      - ./logs:/var/log/supervisor
    environment:
      DISPLAY: ":99"
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
    shm_size: 2gb
    security_opt:
      - seccomp: unconfined
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
